/*
Data scraped:
- Url: https://www.thegioididong.com/dtdd-xiaomi#m:80,2,1971,2235,2236,17201,17566,1,104,19,5332,2327,100,4832&o:5
- Script:
 
var labels = Array.from(document.querySelectorAll('.choosedfilter a:not(.reset)')).map(
  (item) => item.textContent.trim(),
);
JSON.stringify(
  Array.from(document.querySelectorAll('.filter a img')).map((item, id) => ({
    id: `brand_${id + 1}`,
    name: labels[id],
    productIds: [],
  })),
  null,
  2,
);

- Steps: Access the url, open the console window (Ctrl + Shift + I), copy and paste the script to the console, run then see the result

*/

export default [
  {
    id: 'brand_1',
    name: 'iPhone (Apple)',
    image: 'https://cdn.tgdd.vn/Brand/1/iPhone-(Apple)42-b_16.jpg',
    productIds: [
      'product_1',
      'product_2',
      'product_3',
      'product_4',
      'product_5',
      'product_6',
      'product_7',
      'product_8',
      'product_9',
      'product_10',
      'product_11',
      'product_12',
      'product_13',
      'product_14',
      'product_15',
    ],
  },
  {
    id: 'brand_2',
    name: 'Samsung',
    image: 'https://cdn.tgdd.vn/Brand/1/Samsung42-b_25.jpg',
    productIds: [
      'product_16',
      'product_17',
      'product_18',
      'product_19',
      'product_20',
      'product_21',
      'product_22',
      'product_23',
      'product_24',
      'product_25',
      'product_26',
      'product_27',
      'product_28',
      'product_29',
      'product_30',
      'product_31',
      'product_32',
      'product_33',
      'product_34',
      'product_35',
      'product_36',
      'product_37',
      'product_38',
    ],
  },
  {
    id: 'brand_3',
    name: 'OPPO',
    image: 'https://cdn.tgdd.vn/Brand/1/OPPO42-b_9.png',
    productIds: [
      'product_39',
      'product_40',
      'product_41',
      'product_42',
      'product_43',
      'product_44',
      'product_45',
      'product_46',
      'product_47',
      'product_48',
      'product_49',
    ],
  },
  {
    id: 'brand_4',
    name: 'Xiaomi',
    image: 'https://cdn.tgdd.vn/Brand/1/Xiaomi42-b_45.jpg',
    productIds: [
      'product_50',
      'product_51',
      'product_52',
      'product_53',
      'product_54',
      'product_55',
      'product_56',
      'product_57',
      'product_58',
      'product_59',
      'product_60',
      'product_61',
      'product_62',
      'product_63',
      'product_64',
      'product_65',
    ],
  },
  {
    id: 'brand_5',
    name: 'Vivo',
    image: 'https://cdn.tgdd.vn/Brand/1/Vivo42-b_50.jpg',
    productIds: [
      'product_66',
      'product_67',
      'product_68',
      'product_69',
      'product_70',
      'product_71',
      'product_72',
      'product_73',
      'product_74',
      'product_75',
      'product_76',
      'product_77',
      'product_78',
    ],
  },
  {
    id: 'brand_6',
    name: 'Realme',
    image: 'https://cdn.tgdd.vn/Brand/1/Realme42-b_37.png',
    productIds: [
      'product_79',
      'product_80',
      'product_81',
      'product_82',
      'product_83',
      'product_84',
      'product_85',
      'product_86',
      'product_87',
      'product_88',
      'product_89',
      'product_90',
      'product_91',
      'product_92',
      'product_93',
      'product_94',
    ],
  },
  {
    id: 'brand_7',
    name: 'Vsmart',
    image: 'https://cdn.tgdd.vn/Brand/1/Vsmart42-b_40.png',
    productIds: [
      'product_95',
      'product_96',
      'product_97',
      'product_98',
      'product_99',
      'product_100',
      'product_101',
      'product_102',
      'product_103',
      'product_104',
    ],
  },
  {
    id: 'brand_8',
    name: 'Nokia',
    image: 'https://cdn.tgdd.vn/Brand/1/Nokia42-b_21.jpg',
    productIds: [
      'product_105',
      'product_106',
      'product_107',
      'product_108',
      'product_109',
      'product_110',
      'product_111',
      'product_112',
      'product_113',
      'product_114',
      'product_115',
      'product_116',
      'product_117',
      'product_118',
    ],
  },
  {
    id: 'brand_9',
    name: 'Huawei',
    image: 'https://cdn.tgdd.vn/Brand/1/Huawei42-b_30.jpg',
    productIds: [
      'product_119',
      'product_120',
      'product_121',
      'product_122',
      'product_123',
      'product_124',
      'product_125',
      'product_126',
      'product_127',
    ],
  },
  {
    id: 'brand_10',
    name: 'Mobell',
    image: 'https://cdn.tgdd.vn/Brand/1/Mobell42-b_19.jpg',
    productIds: [
      'product_128',
      'product_129',
      'product_130',
      'product_131',
      'product_132',
      'product_133',
      'product_134',
      'product_135',
      'product_136',
      'product_137',
      'product_138',
      'product_139',
      'product_140',
    ],
  },
  {
    id: 'brand_11',
    name: 'Itel',
    image: 'https://cdn.tgdd.vn/Brand/1/Itel42-b_54.jpg',
    productIds: [
      'product_141',
      'product_142',
      'product_143',
      'product_144',
      'product_145',
      'product_146',
      'product_147',
      'product_148',
      'product_149',
      'product_150',
    ],
  },
  {
    id: 'brand_12',
    name: 'Coolpad',
    image: 'https://cdn.tgdd.vn/Brand/1/Coolpad42-b_33.png',
    productIds: [
      'product_151',
      'product_152',
      'product_153',
      'product_154',
      'product_155',
      'product_156',
      'product_157',
    ],
  },
  {
    id: 'brand_13',
    name: 'BlackBerry',
    image: 'https://cdn.tgdd.vn/Brand/1/BlackBerry42-b_38.png',
    productIds: ['product_158', 'product_159', 'product_160', 'product_161', 'product_162'],
  },
  {
    id: 'brand_14',
    name: 'Masstel',
    image: 'https://cdn.tgdd.vn/Brand/1/Masstel42-b_0.png',
    productIds: [
      'product_163',
      'product_164',
      'product_165',
      'product_166',
      'product_167',
      'product_168',
      'product_169',
      'product_170',
      'product_171',
    ],
  },
];
